apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: home
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS employees (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        department VARCHAR(100) NOT NULL
    );

    INSERT INTO employees (name, department) VALUES
    ('Srikanth', 'Engineering'),
    ('Aadya', 'Education'),
    ('John', 'Finance'),
    ('Mary', 'HR'),
    ('David', 'Operations'),
    ('Sarah', 'Engineering'),
    ('Michael', 'Sales'),
    ('Priya', 'Marketing'),
    ('Raj', 'Support'),
    ('Anita', 'Product');